#spring:
#  application:
#    name: eureka-server
#
#  config:
#    import: "configserver:"
#
#  cloud:
#    config:
#      uri: http://config.platform:8888

spring:
  application:
    name: eureka-server

  config:
    import: "configserver:http://config.platform:8888"